name = "aiken-lang/minting-contract"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/minting-contract'"

[repository]
user = "aiken-lang"
project = "minting-contract"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.5.0"
source = "github"
